# Makefile.dep created Tue Feb 17 23:08:49 PST 2015
trace.o: trace.cpp trace.h
util.o: util.cpp util.h trace.h util.tcc
main.o: main.cpp listmap.h xless.h xpair.h listmap.tcc trace.h util.h \
 util.tcc
